/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Authenticate a user using email + password.
         *     Returns a short-lived access token and sets a secure refresh cookie.
         *
         *     Writes 'auth.login' on success and 'auth.login.failed' on failure —
         *     see authenticate_user() in auth_service.py for why the failure entry's
         *     actor is the attempted email rather than a resolved user.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange refresh cookie for new access token
         * @description Exchange a valid refresh token cookie for a new access token.
         *     Stateless: refresh tokens are validated cryptographically, not stored server-side.
         *
         *     Writes 'auth.refresh.failed' to the audit_log DB table on any
         *     rejection. A successful refresh is intentionally NOT written there —
         *     it goes to the structured JSON security log instead. See
         *     rotate_access_token()'s docstring in auth_service.py for the full
         *     reasoning (volume, no target resource, signal-to-noise on the
         *     compliance table).
         *
         *     Note: a missing refresh cookie 401s here without calling the service
         *     at all, so it is not audited or security-logged either way — an
         *     absent cookie is the normal state for a logged-out client, not a
         *     security event.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear refresh token cookie */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List devices (paginated, filterable)
         * @description List devices with optional status/search/OS filters, paginated.
         *     Requires an authenticated user; no role escalation here — matches the
         *     access level of the original unpaginated endpoint.
         */
        get: operations["list_devices_devices__get"];
        put?: never;
        /**
         * Create a device (admin only)
         * @description Create a new device.
         *     Admin-only; enforces uniqueness on ip_address and returns 409 on conflict.
         */
        post: operations["create_device_devices__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a device (admin only)
         * @description Delete a device.
         *     Admin-only; handles missing devices with 404. Writes an audit entry
         *     (with the device's ip/hostname captured before deletion) — see
         *     services/device_service.py's delete_device.
         */
        delete: operations["delete_device_devices__device_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a device (admin only)
         * @description Partially update an existing device.
         *     Admin-only; rejects empty payloads and handles missing devices with 404.
         */
        patch: operations["update_device_devices__device_id__patch"];
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a subnet scan
         * @description Validates the subnet is a private RFC 1918 range, registers a scan job, and schedules it as a background task. Returns immediately with a job_id — use GET /scan/{job_id}/stream to follow progress. Admin role required.
         */
        post: operations["start_scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream scan progress via SSE
         * @description Server-Sent Events stream of a running scan job's progress. Emits 'progress' events per host, then a terminal 'complete' or 'error' event, after which the stream closes. Any authenticated user may watch.
         */
        get: operations["stream_scan_progress_scan__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List onboarded users
         * @description Reads the platform's own operational record (Postgres), not live from whichever directory backend is active. Never includes temporary_password — that value is never persisted anywhere.
         */
        get: operations["list_onboarded_users_onboard_get"];
        put?: never;
        /** Start onboarding a new hire */
        post: operations["onboard_user_onboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboard/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream onboarding progress */
        get: operations["stream_onboarding_progress_onboard_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboard/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** n8n status callback (internal) */
        post: operations["report_job_status_onboard_jobs__job_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboard/{user_id}/offboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Offboard a user
         * @description Revokes directory access for a previously onboarded user — soft-delete (status flip), never a hard delete. Idempotent: re-calling on an already-offboarded user is a no-op that returns the original record.
         */
        post: operations["offboard_user_onboard__user_id__offboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboard/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed onboarding job */
        post: operations["retry_onboarding_onboard_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger manual PDF report generation
         * @description Queues PDF generation via BackgroundTask. Returns a job ID to poll for completion.
         */
        post: operations["trigger_report_reports_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check status of a queued report */
        get: operations["get_report_status_reports__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a completed report PDF
         * @description Downloads the PDF and clears it from server memory. Can only be downloaded once.
         */
        get: operations["download_report_reports__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch scheduled report history */
        get: operations["get_report_history_reports_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit log entries (admin only)
         * @description List audit log entries, newest first, with optional filters.
         *     Admin-only — this table records who did what to whose data, so
         *     read access itself must be restricted, not just write access.
         */
        get: operations["list_audit_logs_audit_logs__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogRead */
        AuditLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string | null;
            /** Target Id */
            target_id: string | null;
            /** Payload */
            payload: Record<string, never> | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** DeviceCreate */
        DeviceCreate: {
            /** Hostname */
            hostname?: string | null;
            /** Ip Address */
            ip_address: string;
            /** Mac Address */
            mac_address?: string | null;
            /** @default unknown */
            status: components["schemas"]["DeviceStatus"];
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Memory Percent */
            memory_percent?: number | null;
            /** Os Info */
            os_info?: string | null;
        };
        /** DeviceRead */
        DeviceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Hostname */
            hostname: string | null;
            /** Ip Address */
            ip_address: string;
            /** Mac Address */
            mac_address: string | null;
            status: components["schemas"]["DeviceStatus"];
            /** Cpu Percent */
            cpu_percent: number | null;
            /** Memory Percent */
            memory_percent: number | null;
            /** Os Info */
            os_info: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Open Ports */
            open_ports: Record<string, never>[] | null;
            /** Last Seen */
            last_seen: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DeviceStatus
         * @enum {string}
         */
        DeviceStatus: "online" | "offline" | "unknown";
        /**
         * DeviceUpdate
         * @description All fields optional — PATCH semantics.
         */
        DeviceUpdate: {
            /** Hostname */
            hostname?: string | null;
            /** Mac Address */
            mac_address?: string | null;
            status?: components["schemas"]["DeviceStatus"] | null;
            /** Cpu Percent */
            cpu_percent?: number | null;
            /** Memory Percent */
            memory_percent?: number | null;
            /** Os Info */
            os_info?: string | null;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatusCallback */
        JobStatusCallback: {
            /**
             * Status
             * @enum {string}
             */
            status: "JIRA_CREATING" | "COMPLETED" | "FAILED";
            /** Error */
            error?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OffboardResponse */
        OffboardResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Status */
            status: string;
            /** Offboarded At */
            offboarded_at: string | null;
        };
        /** OnboardJobStarted */
        OnboardJobStarted: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** OnboardRequest */
        OnboardRequest: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Department */
            department: string;
            /** Job Title */
            job_title: string;
        };
        /** OnboardedUserListItem */
        OnboardedUserListItem: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Job Id */
            job_id: string | null;
            /** External Id */
            external_id: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Department */
            department: string;
            /** Job Title */
            job_title: string;
            /** Status */
            status: string;
            /** Workflow Status */
            workflow_status: string;
            /** Provisioning Source */
            provisioning_source: string;
            /** Requested By */
            requested_by: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Offboarded At */
            offboarded_at: string | null;
        };
        /** PaginatedDeviceList */
        PaginatedDeviceList: {
            /** Data */
            data: components["schemas"]["DeviceRead"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * PaginationMeta
         * @description Deliberately camelCase field NAMES (not aliases) — unlike DeviceRead
         *     above, which mirrors the ORM's snake_case exactly since it'll
         *     eventually be superseded by openapi-typescript codegen. This envelope
         *     is hand-written and only ever consumed by the frontend directly, so
         *     matching its expected shape 1:1 avoids an alias layer for something
         *     that will never come from codegen anyway.
         */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalpages */
            totalPages: number;
            /** Totalitems */
            totalItems: number;
        };
        /** ReportJobResponse */
        ReportJobResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Error Message */
            error_message?: string | null;
        };
        /** ReportRead */
        ReportRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Report Name */
            report_name: string;
            /** Report Type */
            report_type: string;
            /** Triggered By */
            triggered_by: string;
            /** Recipient Emails */
            recipient_email: string;
            /** Status */
            status: string;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
            /** Error Message */
            error_message?: string | null;
        };
        /** ReportTriggerRequest */
        ReportTriggerRequest: {
            /**
             * Report Type
             * @description The classification of the report to generate.
             * @enum {string}
             */
            report_type: "overview" | "asset_inventory" | "device_health" | "onboarding_summary" | "compliance_audit";
            /**
             * Start Date
             * @description Start date for the report data range.
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date for the report data range.
             */
            end_date?: string | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Subnet */
            subnet: string;
        };
        /** ScanStartResponse */
        ScanStartResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @default started
             */
            status: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_devices_devices__get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DeviceStatus"] | null;
                /** @description Matches hostname, IP, or MAC */
                search?: string | null;
                /** @description Substring match against os_info */
                os?: string | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeviceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_devices__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_scan_progress_scan__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_onboarded_users_onboard_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardedUserListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboard_user_onboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardJobStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_onboarding_progress_onboard_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_job_status_onboard_jobs__job_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                "x-callback-secret"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStatusCallback"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offboard_user_onboard__user_id__offboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OffboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_onboarding_onboard_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardJobStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_report_reports_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_status_reports__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_reports__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_history_reports_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRead"][];
                };
            };
        };
    };
    list_audit_logs_audit_logs__get: {
        parameters: {
            query?: {
                actor?: string | null;
                action?: string | null;
                target_type?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
