"""initial schema

Revision ID: 2e05da2c7743
Revises:
Create Date: 2026-08-27 23:31:00.171117

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e05da2c7743"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column(
            "status", sa.Enum("online", "offline", "unknown", name="device_status"), nullable=False
        ),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("memory_percent", sa.Float(), nullable=True),
        sa.Column("os_info", sa.String(length=255), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("open_ports", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_ip_address"), "devices", ["ip_address"], unique=True)
    op.create_table(
        "onboarded_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("job_title", sa.String(length=100), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "OFFBOARDED", name="onboarded_user_status"), nullable=False
        ),
        sa.Column(
            "provisioning_source",
            sa.Enum("LOCAL", "LDAP", "ENTRA_ID", name="provisioning_source"),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column(
            "job_status",
            sa.Enum(
                "PENDING",
                "AD_CREATING",
                "EMAIL_SENDING",
                "JIRA_CREATING",
                "COMPLETED",
                "FAILED",
                name="onboard_job_status",
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_onboarded_user_email"), "onboarded_user", ["email"], unique=True)
    op.create_index(op.f("ix_onboarded_user_job_id"), "onboarded_user", ["job_id"], unique=False)
    op.create_table(
        "report_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_name", sa.String(length=100), nullable=False),
        sa.Column("report_type", sa.String(length=100), nullable=False),
        sa.Column("triggered_by", sa.String(length=255), nullable=False),
        sa.Column("recipient_email", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Enum("SENT", "FAILED", name="report_status_enum"), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "viewer", name="user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "device_health_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_health_history_device_date",
        "device_health_history",
        ["device_id", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_health_history_device_date", table_name="device_health_history")
    op.drop_table("device_health_history")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("report_log")
    op.drop_index(op.f("ix_onboarded_user_job_id"), table_name="onboarded_user")
    op.drop_index(op.f("ix_onboarded_user_email"), table_name="onboarded_user")
    op.drop_table("onboarded_user")
    op.drop_index(op.f("ix_devices_ip_address"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
