"""update report and onboard  table

Revision ID: 2f71265c60c7
Revises: bd1153515e45
Create Date: 2026-08-20 23:59:12.972809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f71265c60c7'
down_revision: Union[str, None] = 'bd1153515e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarded_user', 'job_status',
               existing_type=postgresql.ENUM('PENDING', 'AD_CREATING', 'EMAIL_SENDING', 'JIRA_CREATING', 'COMPLETED', 'FAILED', name='onboard_job_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarded_user', 'job_status',
               existing_type=postgresql.ENUM('PENDING', 'AD_CREATING', 'EMAIL_SENDING', 'JIRA_CREATING', 'COMPLETED', 'FAILED', name='onboard_job_status'),
               nullable=True)
    # ### end Alembic commands ###
