"""update report table

Revision ID: bd1153515e45
Revises: a3ae9e27fecf
Create Date: 2026-08-20 23:40:54.183788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1153515e45'
down_revision: Union[str, None] = 'a3ae9e27fecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('report_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='report_status_enum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('onboarded_user', sa.Column('job_id', sa.String(length=36), nullable=True))
    op.add_column('onboarded_user', sa.Column('job_status', sa.Enum('PENDING', 'AD_CREATING', 'EMAIL_SENDING', 'JIRA_CREATING', 'COMPLETED', 'FAILED', name='onboard_job_status'), nullable=True))
    op.add_column('onboarded_user', sa.Column('requested_by', sa.String(length=255), nullable=True))
    op.add_column('onboarded_user', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_onboarded_user_job_id'), 'onboarded_user', ['job_id'], unique=False)
    # ### end Alembic commands ###

    # 2. Backfill existing rows with a default value
    op.execute(
        "UPDATE onboarded_user SET job_status = 'PENDING' WHERE job_status IS NULL"
    )
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarded_user_job_id'), table_name='onboarded_user')
    op.drop_column('onboarded_user', 'error_message')
    op.drop_column('onboarded_user', 'requested_by')
    op.drop_column('onboarded_user', 'job_status')
    op.drop_column('onboarded_user', 'job_id')
    op.drop_table('report_log')
    # ### end Alembic commands ###
