"""create health history

Revision ID: cfbf9abef528
Revises: 2f71265c60c7
Create Date: 2026-08-22 17:07:21.270906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbf9abef528'
down_revision: Union[str, None] = '2f71265c60c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_health_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_history_device_date', 'device_health_history', ['device_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_history_device_date', table_name='device_health_history')
    op.drop_table('device_health_history')
    # ### end Alembic commands ###
