"""create onboarded_user table

Revision ID: d3570f408c4e
Revises: dbfda33e95e6
Create Date: 2026-08-19 09:27:00.311214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3570f408c4e'
down_revision: Union[str, None] = 'dbfda33e95e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarded_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OFFBOARDED', name='onboarded_user_status'), nullable=False),
    sa.Column('provisioning_source', sa.Enum('LOCAL', 'LDAP', 'ENTRA_ID', name='provisioning_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarded_user_email'), 'onboarded_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarded_user_email'), table_name='onboarded_user')
    op.drop_table('onboarded_user')
    # ### end Alembic commands ###
