"""add latency to Device table

Revision ID: dbfda33e95e6
Revises: 44c36952d57e
Create Date: 2026-08-15 18:11:44.185425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbfda33e95e6'
down_revision: Union[str, None] = '44c36952d57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latency_ms', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'open_ports')
    op.drop_column('devices', 'latency_ms')
    # ### end Alembic commands ###
