# Paste this into the generated migration file's upgrade()/downgrade()
# AFTER running `alembic revision --autogenerate -m "create audit_log table"`.
# Autogenerate will create the table itself correctly; it will NOT create
# this trigger (CW-12) — that part must be added by hand every time.

from alembic import op

def upgrade() -> None:
    # ... autogenerated op.create_table("audit_log", ...) goes here first ...

    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
          RAISE EXCEPTION 'audit_log is append-only: UPDATE and DELETE are not permitted';
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER audit_log_immutability
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_immutability ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_mutation();")

    # ... autogenerated op.drop_table("audit_log") goes here after ...